@startuml
!include <awslib/AWSCommon>
!include <awslib/Compute/EC2>
!include <awslib/Storage/SimpleStorageService>
EC2(app, "AppServer", "SpringBoot")
SimpleStorageService(s3, "ContentsBucket", "")
@enduml
