@startuml
!include <awslib/AWSCommon>
!include <awslib/NetworkingContentDelivery/ElasticLoadBalancing>
!include <awslib/NetworkingContentDelivery/VPCInternetGateway>
!include <awslib/Groups/PublicSubnet>
!include <awslib/Groups/VPC>
!include <awslib/NetworkingContentDelivery/VPCNATGateway>
!include <awslib/Storage/SimpleStorageService>
ElasticLoadBalancing(alb, "FrontendLoadBalancer", "")
VPCInternetGateway(i_gateway, "InternetGateway", "")
VPCNATGateway(nat_gateway_a, "NatGatewayA", "")
VPCNATGateway(nat_gateway_c, "NatGatewayC", "")
SimpleStorageService(s3, "AccessLogsBucket", "")
PublicSubnetGroup(subnet_private_a, "PrivateSubnetA")
PublicSubnetGroup(subnet_private_c, "PrivateSubnetC")
PublicSubnetGroup(subnet_pub_a, "PublicSubnetA")
PublicSubnetGroup(subnet_pub_c, "PublicSubnetC")
VPCGroup(vpc, "Tf2puml_VPC")
@enduml
