name: Attach Artifacts to Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  upload-release-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and prepare artifacts
        run: |
          echo "Building the project and preparing artifacts..."
          mkdir artifacts
          ./mvnw package
          cp target/terra-puml-*-SNAPSHOT.jar artifacts/terra-puml

      - name: Upload artifact to release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/terra-puml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}